In [1]:
#Numpy contains foll types of objects
#1. high level number objects: int, float
#2 containers: lists (costless insertion and append), dictionaries (fast lookup)

In [ ]:
Numpy provides
1. extension package for multi dimension array
2. closer to hardware(better efficiency)
3. designed for scientific computation
4. also known as array oriented computing

In [2]:
import numpy as np

a = np.array([0,1,2,3])
print(a)

print(np.arange(10))

[0 1 2 3]
[0 1 2 3 4 5 6 7 8 9]


In [3]:
#memory efficient

In [ ]:
%timeit runs the given iteration multiple times and calculates how much time it took per iteration

In [5]:
l = range(1000)
%timeit [i**2 for i in l]

263 µs ± 11 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [ ]:
#it took 263microseconds mean and 11microseconds SD for a python list

In [7]:
a = np.arange(1000)
%timeit a**2

1.67 µs ± 53.3 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


In [8]:
#it took 1.67microsecond mean and sd is 53.3 microseconds for a numpy array
#therefore numpy is memory efficient and super fast (close to 200 times faster)

In [9]:
#1D array (vector)

In [10]:
a = np.array([0,1,2,3])
print(a)

print(a.ndim) #dimension of array

print(a.shape) #shape of the array

print(len(a))

[0 1 2 3]
1
(4,)
4


In [3]:
#2D (matrix)
a = np.array([[0,1,2],[3,4,5], [0,1,2]]) #provide a list of lists
print(a) 

print(a.ndim) #dimension of array

print(a.shape) #shape of the array

print(len(a)) #returns the size of 1st dimension ie no. of rows = 2

[[0 1 2]
 [3 4 5]
 [0 1 2]]
2
(3, 3)
3


In [14]:
#3D array (grid/cube structure)
#n dimension array is called a Tensor
a = np.array([[[1,2],[3,4]], [[4,5],[6,7]]]) #provide a list of lists
print(a) 

print(a.ndim) #dimension of array

print(a.shape) #shape of the array, there are 2 matrices each with 2 rows and 2 cols

print(len(a)) #returns the size of 1st dimension ie no. of rows = 2

[[[1 2]
  [3 4]]

 [[4 5]
  [6 7]]]
3
(2, 2, 2)
2


In [15]:
#create array
#arange(start, end, step) default step=1

In [16]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [17]:
a = np.arange(1,10, 2)
a

array([1, 3, 5, 7, 9])

In [4]:
#linspace(start, end, number_of_points) #including start and end
#linear space ie it divides a line which starts from the given start and ends at a given end and it divides the line into number_of_points equal parts
#the differnce between 2 points is the same
a = np.linspace(0,1,6)
a

array([0. , 0.2, 0.4, 0.6, 0.8, 1. ])

In [6]:
#ones takes a tuple(row,column) as i/p
a = np.ones((3,3))
print(a)
print("*****************")
print(np.ones(3))

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
*****************
[1. 1. 1.]


In [7]:
#zeros takes a tuple(row,column) as i/p
a = np.zeros((3,3))
print(a)
print("*****************")
print(np.zeros(3))

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
*****************
[0. 0. 0.]


In [8]:
#identity matrix
print(np.eye(3))
print("*******************")
np.eye(3,2) #(rows, cols)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
*******************


array([[1., 0.],
       [0., 1.],
       [0., 0.]])

In [9]:
#Diagonal: construct a diagonal matrix
a = np.diag([1,2,3,4])
print(a)
print("**************************")
#print the diagnoal elements of a matrix
print(np.diag(a))

[[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]
**************************
[1 2 3 4]


In [6]:
#create random nos

In [3]:
a = np.random.rand(4) #array of size 4 of uniform distributed random no

In [8]:
a = np.random.randn(4) #array of size 4 of std normal/gaussian dist random no
a

array([ 0.37365348, -0.01516339,  1.28429855, -1.55323845])

In [15]:
#Data Types of Numpy

In [10]:
a = np.arange(10)
a.dtype #datatype: datatype of a

dtype('int32')

In [13]:
a = np.arange(10,dtype="float64")
print(a.dtype)
print(a)

float64
[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


In [14]:
#zeros and ones always creates float datatype matrix
a = np.zeros((3,3))
a.dtype

dtype('float64')

In [16]:
#complex datatype
d = np.array([1+2j, 3+8j])
d.dtype

dtype('complex128')

In [17]:
#boolean datatype
d = np.array([True, False, False])
d.dtype

dtype('bool')

In [18]:
#string datatype
d = np.array(["aaa", "add", "qqq"])
d.dtype

dtype('<U3')

In [19]:
#Indexing and Slicing

In [20]:
a = np.arange(10)
a[6]

6

In [22]:
#multidimension
a = np.diag([1,2,3])
a[2][2] # or a[2,2]

3

In [23]:
#assigning value
a[2,1] = 5 #or a[2][1] = 5
a

array([[1, 0, 0],
       [0, 2, 0],
       [0, 5, 3]])

In [24]:
#Slicing

In [25]:
a = np.arange(10)

In [26]:
a[1:8:2] #[start, stop, step]

array([1, 3, 5, 7])

In [12]:
a = np.arange(10)
a[5:] = 10
a

array([ 0,  1,  2,  3,  4, 10, 10, 10, 10, 10])

In [15]:
b = np.arange(5)
a[5:] = b[::-1] #step in negative(reverse) direction
a

array([0, 1, 2, 3, 4, 4, 3, 2, 1, 0])

In [31]:
#Copies and Views

In [32]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [33]:
b = a[::2]
b

array([0, 2, 4, 6, 8])

In [34]:
#Numpy internally points a and b to the same memory location. b points to the sub array of a
#This is for memory optimization, b points to the same location but uses the sub array ie internally Numpy uses View
#View means there is no copy of array, but a differnt methodology is used to create the sub array b for space efficiency
np.shares_memory(a,b)

True

In [36]:
b[0] = 10
b

array([10,  2,  4,  6,  8])

In [37]:
a
# since a and b point to the same memory location, if b is modified a will also be modified

array([10,  1,  2,  3,  4,  5,  6,  7,  8,  9])

In [38]:
#to create different copies use the copy()
a = np.arange(10)
c = a[::2].copy()
c

array([0, 2, 4, 6, 8])

In [39]:
np.shares_memory(a,c)

False

In [40]:
#Fancy Indexing
#Numpy arrays can be indexed with boolean or integer arrays (masks). It creates copies not views

In [42]:
a = np.random.randint(0,20,15) #(start, end, number_of_numbers_needed)
a

array([14,  6,  6, 18,  5, 14,  1, 12, 19, 15,  7,  4, 18,  7,  3])

In [43]:
mask = (a % 2 == 0)
mask

array([ True,  True,  True,  True, False,  True, False,  True, False,
       False, False,  True,  True, False, False])

In [44]:
extract_from_a = a[mask] #get all even nos ie extract true values
extract_from_a

array([14,  6,  6, 18, 14, 12,  4, 18])

In [46]:
a[mask] = -1 #converts all even nos to -1
a

array([-1, -1, -1, -1,  5, -1,  1, -1, 19, 15,  7, -1, -1,  7,  3])

In [47]:
#Indexing with array of integers

In [48]:
a = np.arange(0,100,10)
a

array([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [16]:
#inner array is a list of indexes, same index can be repeated
print(a[[2,3,2,4,2]])
print(a)

[2 3 2 4 2]
[0 1 2 3 4 4 3 2 1 0]


In [52]:
#assign new values
a[[9,7]] = -100
a

array([   0,   10,   20,   30,   40,   50,   60, -100,   80, -100])