In [3]:
import numpy as np

In [2]:
#elementwise operations

In [3]:
#scalars

In [6]:
a = np.array([1,2,3,4])
print(a+1)
print(a ** 2)

[2 3 4 5]
[ 1  4  9 16]


In [7]:
b = np.ones(4) + 1
b

array([2., 2., 2., 2.])

In [9]:
a

array([1, 2, 3, 4])

In [8]:
a - b #elementwise subtraction

array([-1.,  0.,  1.,  2.])

In [10]:
a * b #elementwise multiplication

array([2., 4., 6., 8.])

In [13]:
#Matrix multiplication
c = np.diag([1,2,3,4])
print(c*c) #matrix elementwise multiplication with matrices having the same shape
print("*******************")
print(c.dot(c))

[[ 1  0  0  0]
 [ 0  4  0  0]
 [ 0  0  9  0]
 [ 0  0  0 16]]
*******************
[[ 1  0  0  0]
 [ 0  4  0  0]
 [ 0  0  9  0]
 [ 0  0  0 16]]


In [15]:
#element wise comparison
a = np.array([1,2,3,4])
b = np.array([5,2,2,4])
print(a == b) #element wise comparison
print(a > b) #element wise comparison

[False  True False  True]
[False False  True False]


In [16]:
#array wise comparision
a = np.array([1,2,3,4])
b = np.array([5,2,2,4])
c = np.array([1,2,3,4])

print(np.array_equal(a,b))
print(np.array_equal(a,c))

False
True


In [19]:
#Logical Operations
a = np.array([1,1,0,0], dtype=bool)
b = np.array([1,0,1,0], dtype=bool)

print(np.logical_or(a,b))
print(np.logical_and(a,b))

[ True  True  True False]
[ True False False False]


In [23]:
#Transcedental Functions
a = np.arange(5)
print(np.sin(a))
print(np.log(a))
print(np.exp(a)) #evaluates e^ x

[ 0.          0.84147098  0.90929743  0.14112001 -0.7568025 ]
[      -inf 0.         0.69314718 1.09861229 1.38629436]
[ 1.          2.71828183  7.3890561  20.08553692 54.59815003]


In [24]:
#Shape mismatch
a = np.arange(4)
a + np.arange([1,2]) #cannot add 2 arrays with differnt no of elements

TypeError: unsupported operand type(s) for -: 'list' and 'int'

In [25]:
#Basic Reductions

In [26]:
x = np.array([1,2,3,4])
np.sum(x)

10

In [30]:
#sum by rows and columns
x = np.array([[1,1], [2,2]])
print(x)
print("************")
print(x.sum(axis=0)) #axis=0 means column wise sum ie 1+2 and 1+2
print("************")
print(x.sum(axis=1)) #axis=1 means row wise sum ie 1+1 and 2+2

[[1 1]
 [2 2]]
************
[3 3]
************
[2 4]


In [32]:
x = np.array([1,2,3,4])
print(x.min())
print(x.max())
print(x.argmin()) #at what index is the minimum value
print(x.argmax()) #at what index is the maximum value

1
4
0
3


In [33]:
#Logical Operations (any, all)

In [35]:
print(np.all([True, False, True])) #returns True if all are True (AND)
np.any([True, False, False]) #returns True if anyone is True (OR)

False


True

In [37]:
#can be used for array comparision
a = np.zeros((50,50))
print(np.any(a != 0)) #is there any element which != 0?
print(np.all(a == a)) #are all elements of a equal to each other

False
True


In [38]:
a = np.array([1,2,3,2])
b = np.array([2,2,3,2])
c = np.array([6,4,4,5])

((a <= b) & (b <= c)).all() #[T,T,T,T] & [T,T,T,T].all() = True

True

In [39]:
#Statistics
#axis=0 means columns
#axis=1 means rows
#axis=-1 means last axis which is rows

In [41]:
x = np.array([1,2,3,1])
y = np.array([[1,2,3], [5,6,1]])

print(x.mean())
print(np.median(x))
print(np.median(y, axis=-1)) #median on last axis which is rows
print(x.std()) #population SD

1.75
1.5
[2. 5.]
0.82915619758885


In [42]:
#Example
#Data in populations.txt describes the population of hares(rabbit) and lynxes(wild cats) and carrots in nothern Canada during 20 years
#Rabbits eat carrots, Wild Cats eat Rabbits

In [4]:
#load data into numpy array object
data = np.loadtxt("populations.txt")
data

array([[ 1900., 30000.,  4000., 48300.],
       [ 1901., 47200.,  6100., 48200.],
       [ 1902., 70200.,  9800., 41500.],
       [ 1903., 77400., 35200., 38200.],
       [ 1904., 36300., 59400., 40600.],
       [ 1905., 20600., 41700., 39800.],
       [ 1906., 18100., 19000., 38600.],
       [ 1907., 21400., 13000., 42300.],
       [ 1908., 22000.,  8300., 44500.],
       [ 1909., 25400.,  9100., 42100.],
       [ 1910., 27100.,  7400., 46000.],
       [ 1911., 40300.,  8000., 46800.],
       [ 1912., 57000., 12300., 43800.],
       [ 1913., 76600., 19500., 40900.],
       [ 1914., 52300., 45700., 39400.],
       [ 1915., 19500., 51100., 39000.],
       [ 1916., 11200., 29700., 36700.],
       [ 1917.,  7600., 15800., 41800.],
       [ 1918., 14600.,  9700., 43300.],
       [ 1919., 16200., 10100., 41300.],
       [ 1920., 24700.,  8600., 47300.]])

In [5]:
year, hares, lynxes, carrots = data.T #transpose of data and assign to respective lists
year

array([1900., 1901., 1902., 1903., 1904., 1905., 1906., 1907., 1908.,
       1909., 1910., 1911., 1912., 1913., 1914., 1915., 1916., 1917.,
       1918., 1919., 1920.])

In [6]:
#mean population over time
populations = data[:,1:]
print(populations)
print("*************")
print(populations.mean())

[[30000.  4000. 48300.]
 [47200.  6100. 48200.]
 [70200.  9800. 41500.]
 [77400. 35200. 38200.]
 [36300. 59400. 40600.]
 [20600. 41700. 39800.]
 [18100. 19000. 38600.]
 [21400. 13000. 42300.]
 [22000.  8300. 44500.]
 [25400.  9100. 42100.]
 [27100.  7400. 46000.]
 [40300.  8000. 46800.]
 [57000. 12300. 43800.]
 [76600. 19500. 40900.]
 [52300. 45700. 39400.]
 [19500. 51100. 39000.]
 [11200. 29700. 36700.]
 [ 7600. 15800. 41800.]
 [14600.  9700. 43300.]
 [16200. 10100. 41300.]
 [24700.  8600. 47300.]]
*************
32215.873015873014


In [48]:
#sample sd
populations.std(axis=0) #columns

array([20897.90645809, 16254.59153691,  3322.50622558])

In [49]:
#which species has the highest population each year?
np.argmax(populations, axis=1) #returns the index of the highest poplulation among hares, lynxes, carrots(rows)

array([2, 2, 0, 0, 1, 1, 2, 2, 2, 2, 2, 2, 0, 0, 0, 1, 2, 2, 2, 2, 2],
      dtype=int64)

In [50]:
#Broadcasting
#Basic operations on numpy arrays(addition, subtraction) are elementwise
#This works on arrays of same size. Its also possible to do operations on arrays of different sizes if NumPy can transform these arrays so that they will have the same size, this conversion is called Broadcasting
#refer images of 5.2

In [55]:
a = np.tile(np.arange(0,40,10),(3,1)) #replicate 1D array created from arange 3 times to create a 2d array which has 3 rows and 4 columns
print(a)
print("******************")
a = a.T
print(a)

[[ 0 10 20 30]
 [ 0 10 20 30]
 [ 0 10 20 30]]
******************
[[ 0  0  0]
 [10 10 10]
 [20 20 20]
 [30 30 30]]


In [56]:
b = np.array([0,1,2])
b

array([0, 1, 2])

In [57]:
a + b #broadcasting

array([[ 0,  1,  2],
       [10, 11, 12],
       [20, 21, 22],
       [30, 31, 32]])

In [65]:
a = np.arange(0, 40, 10)
a.shape

(4,)

In [66]:
#convert to a 2D array to perform such broadcasting shown in 3rd image of 5.2
a = a[:, np.newaxis] #adds a new dimension/axis - here column to the array
print(a)
print(a.shape) # a is a 2D array with 4 rows and 1 columns

[[ 0]
 [10]
 [20]
 [30]]
(4, 1)


In [67]:
a + b #broadcasting

array([[ 0,  1,  2],
       [10, 11, 12],
       [20, 21, 22],
       [30, 31, 32]])

In [68]:
##Array shape Manipulation

In [69]:
#flattening

In [70]:
a = np.array([[1,2,3], [4,5,6]]) #2d array
a

array([[1, 2, 3],
       [4, 5, 6]])

In [71]:
a.ravel() #returns a contagious flattened array which is 1D containing the elements of the 2D array

array([1, 2, 3, 4, 5, 6])

In [72]:
a.T

array([[1, 4],
       [2, 5],
       [3, 6]])

In [73]:
a.T.ravel()

array([1, 4, 2, 5, 3, 6])

In [74]:
#reshaping

In [76]:
print(a.shape)
print(a)

(2, 3)
[[1 2 3]
 [4 5 6]]


In [77]:
b = a.ravel()
b

array([1, 2, 3, 4, 5, 6])

In [83]:
b = b.reshape(2,3) #(rows,columns)

In [87]:
b[0,0] = 100
print(b)
print("*********")
print(a)

[[100   2   3]
 [  4   5   6]]
*********
[[100   2   3]
 [  4   5   6]]


In [88]:
#beware numpy internally stores the matrix in the same memory location for a and b bcoz of memory optimization. Inspite of reshaping and flattening, the memory location of a and b is the same

In [91]:
#reshape may also return a copy sometimes!
a = np.zeros((3,2))
b = a.T.reshape(3,2)
b[0] = 50
a

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [92]:
#Dimension reshuffling

In [93]:
z = np.array([1,2,3])
z

array([1, 2, 3])

In [94]:
z[:,np.newaxis] #converts z to a 2D array

array([[1],
       [2],
       [3]])

In [97]:
a = np.arange(4*3*2).reshape(4,3,2) #reshape to a 3D array which has 4 matrices with 3 rows and 2 columns
a

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5]],

       [[ 6,  7],
        [ 8,  9],
        [10, 11]],

       [[12, 13],
        [14, 15],
        [16, 17]],

       [[18, 19],
        [20, 21],
        [22, 23]]])

In [99]:
a.shape

(4, 3, 2)

In [100]:
a[0,2,1]

5

In [101]:
#resizing

In [102]:
a = np.arange(4)
a.resize((8,)) #resizes to 8 elements but adds 0s where there are no elements
a

array([0, 1, 2, 3, 0, 0, 0, 0])

In [105]:
b = a
a.resize((6,)) #does not permit resize when 2 variables are referring to the same array

ValueError: cannot resize an array that references or is referenced
by another array in this way.
Use the np.resize function or refcheck=False

In [107]:
#sorting data

In [108]:
a = np.array([[5,4,6], [2,3,2]])
b = np.sort(a, axis=1) #sort row-wise
b

array([[4, 5, 6],
       [2, 2, 3]])

In [109]:
#inplace sort
a.sort(axis=1)
a

array([[4, 5, 6],
       [2, 2, 3]])

In [110]:
#sorting with fancy indexing
a = np.array([4,5,1,2])
j = np.argsort(a) #sorts nos and returns the position of indexes of the sorted values
j

array([2, 3, 0, 1], dtype=int64)

In [111]:
a[j]

array([1, 2, 4, 5])